### PR TITLE
commands/auth: fix 0-return on unsuccessful login attempts

### LINKED ISSUE #454: auth login exits with status 0 even for a non-working URL
## Steps to reproduce
**Note** the literal use of example.com here; don't replace it with an actual, working MM instance URL.

    # /usr/bin/sudo -u mattermost /usr/local/bin/mmctl  auth login http://example.com --name example --access-token 123456890abcdefghijklmnopq`
    # echo $?

## What I expect happen
For a non-zero exit status to be printed.

## What happens instead
The exit status is 0.

### PR DESCRIPTION
**Pull request by isacikgoz**
An unsuccessful command should always return a non zero return value, this PR aims to fix this issue.
 
#### Summary
Fixes #454

### CODE REVIEW

File: commands/auth.go [hunk 1]
```diff
@@ -211,7 +211,7 @@ func loginCmdF(cmd *cobra.Command, args []string) error {
 		if err != nil {
 			printer.PrintError(err.Error())
 			// We don't want usage to be printed as the command was correctly built
```
Comment (agnivade) [inline commands/auth.go:213]: This makes the comment invalid. Let's remove it? Also, does this print the usage? I remember there was a flag to disable printing usage for every single error.

Comment (isacikgoz) [reply commands/auth.go]: Good catch! In fact, we don't need to print the error via printer as well. It's already being printed from command output.

**Review by agnivade — APPROVED** [review]
Nice!
