### PR TITLE
commands/auth: use printer instead of fmt.Println

### LINKED ISSUE #433: --quiet not honored by auth login (possibly others)
## Steps to reproduce
1. Log in using mmctl.

## What I expect to happen

    # /usr/bin/sudo -u mattermost /usr/local/bin/mmctl --quiet auth login https://example.com --name example --access-token 123456890abcdefghijklmnopq
    # 

## What happens instead

    # /usr/bin/sudo -u mattermost /usr/local/bin/mmctl --quiet auth login https://example.com --name example --access-token 123456890abcdefghijklmnopq
    
      credentials for "example": "Personal Access Token@https://example.com" stored
    
    # 

## Potential cause
From looking at the code, output and `--quiet` are implemented in `Printer`, but [`auth` and a few other places](https://github.com/mattermost/mmctl/search?q=printf) appear to use `fmt.Printf()` directly instead.

### PR DESCRIPTION
**Pull request by isacikgoz**
#### Summary
Fixes #433

### CODE REVIEW

File: commands/auth.go [hunk 1]
```diff
@@ -247,7 +247,7 @@ func loginCmdF(cmd *cobra.Command, args []string) error {
 		}
 	}
 
-	fmt.Printf("\n  credentials for %q: \"%s@%s\" stored\n\n", name, username, url)
+	printer.Print(fmt.Sprintf("\n  credentials for %q: \"%s@%s\" stored\n", name, username, url))
```
Comment (agnivade) [inline commands/auth.go:250]: Wondering how much work it would be to add a `printer.Printf` interface method as well, (to avoid Sprinting this into the same method)? It's out of scope for this PR, and we can totally create a separate HW ticket if you prefer. Just wanted to get an idea of the effort.

Comment (isacikgoz) [reply commands/auth.go:250]: Hmm, the printer in mmctl is more `text/template` oriented, as the value is being used in a template always. If you are thinking adding another method as `printer.Printf(format string, a ...any)`, I think it would be pretty easy if we just execute a fmt.Sprintf and use printer.Print function. Ie:
```Go
func Printf(format string, a ...interface{}) {
	s := fmt.Sprintf(format, a...)
	Print(s)
}
```
The reason I didn't add this was it was not sharing the same mindset with `printer.Print` as `fmt.Print` does with `fmt.Printf` etc.

Comment (agnivade) [reply commands/auth.go:250]: I see, okay then I don't see a need. This is fine as it is.
