### PR TITLE
mmctl plugin add: introduce optional 'force' flag to allow existing plugins to be replaced

### LINKED ISSUE #382: mmctl: provide an option to allow existing plugins to be replaced during 'mmctl plugin add'
#### Summary
The `mmctl plugin add` command does not currently support replacement of existing plugins, something that is possible when uploading plugins using the Mattermost System Console.

As a workaround, it's possible to use `mmctl plugin delete` to remove an existing plugin prior to the `add` operation.

It could be convenient to have an (opt-in) ability to replace existing plugins.

#### Steps to reproduce
1. Upload a plugin (either using the System Console, or using `mmctl`)
2. Attempt to upload the same plugin again using `mmctl plugin add`

#### Observed behavior (that appears unintentional) 
The following error appears:

```
Unable to add plugin: dist/example-plugin-1.0.0.tgz. Error: : Unable to install plugin. A plugin with the same ID is already installed.
```

#### Possible fixes
The `replace` parameter to `InstallPlugin` is currently [fixed to `false`](https://github.com/mattermost/mattermost-server/blob/bf1f60d309998429b4cd17ea329215b0a0080c40/cmd/mattermost/commands/plugin.go#L123); that could be adjusted to accept a flag from the command-line.

### PR DESCRIPTION
**Pull request by jayaddison-collabora**
#### Summary
This allows users to add a plugin with add-and-replace-if-exists semantics when using the `mmctl plugin add`, by specifying the `--force` flag.

This is implemented by calling the `client.UploadPluginForced` function.

Supercedes mattermost/mattermost-server#18081 and resolves #382.

### CODE REVIEW

File: commands/plugin_test.go [hunk 1]
```diff
@@ -37,6 +37,29 @@ func (s *MmctlUnitTestSuite) TestPluginAddCmd() {
 		s.Require().Equal(printer.GetLines()[0], "Added plugin: "+pluginName)
 	})
 
+	s.Run("Add 1 plugin, with force active", func() {
```
[the remark this answers is not in the document]
Comment (isacikgoz) [reply commands/plugin_test.go:42]: Indeed it is, you can add a test to `*MmctlE2ETestSuite.TestPluginAddCmd()` in the `plugin_e2e_test.go` file as the flag mainly important for the server and results can be observed from there.

**Review by isacikgoz — CHANGES_REQUESTED** [review]
Thanks for the contribution @jayaddison-collabora 🚀 Implementation wise looks good, however, we should add an end to end test to verify the process. Let me know if you need some help for it.

File: commands/plugin_test.go (hunk 1 above)
[the remark this answers is not in the document]
Comment (jayaddison-collabora) [reply commands/plugin_test.go:42]: Thanks @isacikgoz - I've added some end-to-end tests here; again I'm not sure they're the neatest / highest quality tests yet, but I'd be happy to clean them up with a bit of guidance.

**Comment by jayaddison-collabora** [comment]
:wave: Hi @isacikgoz - could you let me know what you think of the end-to-end tests added here?

File: commands/plugin_e2e_test.go [hunk 2]
```diff
@@ -22,6 +22,82 @@ func (s *MmctlE2ETestSuite) TestPluginAddCmd() {
...
+		err := pluginAddCmdF(c, &cobra.Command{}, []string{pluginPath})
+		s.Require().Nil(err)
+
+		s.Require().Equal(1, len(printer.GetLines()))
+		s.Require().Contains(printer.GetLines()[0], "Added plugin: ")
+
+		err = pluginAddCmdF(c, &cobra.Command{}, []string{pluginPath})
+		s.Require().Nil(err)
+
+		s.Require().Equal(1, len(printer.GetLines()))
```
Comment (isacikgoz) [inline commands/plugin_e2e_test.go:47]: I think we should clean the `printer` after we first install the plugin successfully then check that printer does not have any regular output in case of an error.

File: commands/plugin_e2e_test.go [hunk 3]
```diff
@@ -22,6 +22,82 @@ func (s *MmctlE2ETestSuite) TestPluginAddCmd() {
...
+		s.Require().Equal(1, len(printer.GetErrorLines()))
+		s.Require().Contains(printer.GetErrorLines()[0], "Unable to add plugin")
```
Comment (isacikgoz) [inline commands/plugin_e2e_test.go:49]: I think checking this string is not necessary as the check below has a pretty concise error message.

File: commands/plugin_e2e_test.go [hunk 4]
```diff
@@ -22,6 +22,82 @@ func (s *MmctlE2ETestSuite) TestPluginAddCmd() {
...
+
+		s.Require().Equal(1, len(printer.GetLines()))
+		s.Require().Contains(printer.GetLines()[0], "Added plugin: ")
+
+		cmd := &cobra.Command{}
+		cmd.Flags().Bool("force", true, "")
+		err = pluginAddCmdF(c, cmd, []string{pluginPath})
+		s.Require().Nil(err)
+
+		s.Require().Equal(2, len(printer.GetLines()))
```
Comment (isacikgoz) [inline commands/plugin_e2e_test.go:87]: Shall we check if the output is as expected? (also please clean the printer as I mentioned above)

**Review by isacikgoz — CHANGES_REQUESTED** [review]
Great job @jayaddison-collabora 💪 This is almost there! Just some minor checks are required. (please re-request the review when this is ready, otherwise I won't get notified)

**Review by isacikgoz — APPROVED** [review]
Awesome! @jayaddison-collabora thanks for all the effort 🚀
